namespace AgainstRomeMapEditor.Modules.Soundscape;

/// <summary>
/// 環境音效區域編輯器模組。
/// 實作標準 IEditorModule 契約，管理音效區域的工作中狀態、快照捕捉、
/// 交易基線確認、復原/重做歷史與變更重設。
/// </summary>
public sealed class SoundscapeEditorModule : IEditorModule<SoundscapeSnapshot>
{
    private readonly List<SoundscapeZone> _zones = [];
    private string _globalAmbienceId = "Amb_Plains_Wind";
    private float _globalAmbienceVolume = 0.6f;

    private SoundscapeSnapshot _baseline;
    private readonly Stack<SoundscapeSnapshot> _undoStack = new();
    private readonly Stack<SoundscapeSnapshot> _redoStack = new();

    public string ModuleId => "SoundscapeZones";

    public bool IsDirty => !SnapshotsEqual(Capture(), _baseline);

    public string GlobalAmbienceId
    {
        get => _globalAmbienceId;
        set
        {
            if (_globalAmbienceId != value)
            {
                PushUndo();
                _globalAmbienceId = value;
            }
        }
    }

    public float GlobalAmbienceVolume
    {
        get => _globalAmbienceVolume;
        set
        {
            if (Math.Abs(_globalAmbienceVolume - value) > 1e-4f)
            {
                PushUndo();
                _globalAmbienceVolume = value;
            }
        }
    }

    public IReadOnlyList<SoundscapeZone> Zones => _zones.AsReadOnly();

    public SoundscapeEditorModule()
    {
        _baseline = new SoundscapeSnapshot(_globalAmbienceId, _globalAmbienceVolume, []);
    }

    public void Load(SoundscapeSnapshot snapshot)
    {
        ArgumentNullException.ThrowIfNull(snapshot);

        _zones.Clear();
        foreach (var z in snapshot.Zones)
            _zones.Add(z.Clone());

        _globalAmbienceId = snapshot.GlobalAmbienceId;
        _globalAmbienceVolume = snapshot.GlobalAmbienceVolume;

        _baseline = Capture();
        _undoStack.Clear();
        _redoStack.Clear();
    }

    public SoundscapeSnapshot Capture()
    {
        var copiedZones = _zones.Select(z => z.Clone()).ToList();
        return new SoundscapeSnapshot(_globalAmbienceId, _globalAmbienceVolume, copiedZones);
    }

    public void AcceptChanges()
    {
        _baseline = Capture();
    }

    public void Reset()
    {
        Load(_baseline);
    }

    #region 編輯操作與 Undo/Redo

    public void AddZone(SoundscapeZone zone)
    {
        ArgumentNullException.ThrowIfNull(zone);
        PushUndo();
        _zones.Add(zone.Clone());
    }

    public bool RemoveZone(Guid zoneId)
    {
        int idx = _zones.FindIndex(z => z.Id == zoneId);
        if (idx >= 0)
        {
            PushUndo();
            _zones.RemoveAt(idx);
            return true;
        }
        return false;
    }

    public bool UpdateZone(SoundscapeZone updated)
    {
        ArgumentNullException.ThrowIfNull(updated);
        int idx = _zones.FindIndex(z => z.Id == updated.Id);
        if (idx >= 0)
        {
            PushUndo();
            _zones[idx] = updated.Clone();
            return true;
        }
        return false;
    }

    public void AddAutoGeneratedZones(IEnumerable<SoundscapeZone> newZones)
    {
        ArgumentNullException.ThrowIfNull(newZones);
        var list = newZones.ToList();
        if (list.Count == 0) return;

        PushUndo();
        foreach (var z in list)
        {
            var clone = z.Clone();
            clone.Flags |= SoundscapeZoneFlags.IsAutoGenerated;
            _zones.Add(clone);
        }
    }

    public int ClearAutoGeneratedZones()
    {
        var toRemove = _zones.Where(z => z.Flags.HasFlag(SoundscapeZoneFlags.IsAutoGenerated)).ToList();
        if (toRemove.Count == 0)
            return 0;

        PushUndo();
        foreach (var z in toRemove)
            _zones.Remove(z);

        return toRemove.Count;
    }

    public bool CanUndo => _undoStack.Count > 0;
    public bool CanRedo => _redoStack.Count > 0;

    public bool Undo()
    {
        if (_undoStack.Count == 0)
            return false;

        _redoStack.Push(Capture());
        var prev = _undoStack.Pop();
        ApplySnapshotDirect(prev);
        return true;
    }

    public bool Redo()
    {
        if (_redoStack.Count == 0)
            return false;

        _undoStack.Push(Capture());
        var next = _redoStack.Pop();
        ApplySnapshotDirect(next);
        return true;
    }

    private void PushUndo()
    {
        _undoStack.Push(Capture());
        _redoStack.Clear();
    }

    private void ApplySnapshotDirect(SoundscapeSnapshot snapshot)
    {
        _zones.Clear();
        foreach (var z in snapshot.Zones)
            _zones.Add(z.Clone());

        _globalAmbienceId = snapshot.GlobalAmbienceId;
        _globalAmbienceVolume = snapshot.GlobalAmbienceVolume;
    }

    private static bool SnapshotsEqual(SoundscapeSnapshot a, SoundscapeSnapshot b)
    {
        if (a.GlobalAmbienceId != b.GlobalAmbienceId) return false;
        if (Math.Abs(a.GlobalAmbienceVolume - b.GlobalAmbienceVolume) > 1e-4f) return false;
        if (a.Zones.Count != b.Zones.Count) return false;

        for (int i = 0; i < a.Zones.Count; i++)
        {
            var za = a.Zones[i];
            var zb = b.Zones[i];
            if (za.Id != zb.Id) return false;
            if (za.Name != zb.Name) return false;
            if (za.SoundDefId != zb.SoundDefId) return false;
            if (za.ShapeType != zb.ShapeType) return false;
            if (za.AttenuationCurve != zb.AttenuationCurve) return false;
            if (za.Category != zb.Category) return false;
            if (Math.Abs(za.BaseVolume - zb.BaseVolume) > 1e-4f) return false;
            if (Math.Abs(za.InnerRadius - zb.InnerRadius) > 1e-4f) return false;
            if (Math.Abs(za.OuterRadius - zb.OuterRadius) > 1e-4f) return false;
            if (Math.Abs(za.CenterWorldX - zb.CenterWorldX) > 1e-4f) return false;
            if (Math.Abs(za.CenterWorldZ - zb.CenterWorldZ) > 1e-4f) return false;
            if (Math.Abs(za.ParamA - zb.ParamA) > 1e-4f) return false;
            if (Math.Abs(za.ParamB - zb.ParamB) > 1e-4f) return false;
            if (Math.Abs(za.ParamAngleDeg - zb.ParamAngleDeg) > 1e-4f) return false;
            if (za.Flags != zb.Flags) return false;
            if (za.Priority != zb.Priority) return false;
            if (za.PolygonVertices.Count != zb.PolygonVertices.Count) return false;

            for (int vi = 0; vi < za.PolygonVertices.Count; vi++)
            {
                if (Math.Abs(za.PolygonVertices[vi].X - zb.PolygonVertices[vi].X) > 1e-4f ||
                    Math.Abs(za.PolygonVertices[vi].Z - zb.PolygonVertices[vi].Z) > 1e-4f)
                    return false;
            }
        }

        return true;
    }

    #endregion
}
