global using SoundscapeZoneFlags = AgainstRomeMapEditor.Modules.Soundscape.SoundscapeZoneAttributes;

namespace AgainstRomeMapEditor.Modules.Soundscape;

/// <summary>
/// 音效區域幾何形狀類型。
/// </summary>
public enum SoundscapeShapeType : byte
{
    /// <summary>點音源（營火、鐵匠鋪、瀑布落水點、微型神龕）。</summary>
    Point = 0,

    /// <summary>圓形分佈區（湖泊、水潭、聚落環狀氛圍）。</summary>
    Circle = 1,

    /// <summary>定向矩形區域（河谷、邊界風帶、狹長林道）。</summary>
    OrientedRectangle = 2,

    /// <summary>凸多邊形區域（自訂複雜地景、森林外圍包絡線、山谷盆地）。</summary>
    ConvexPolygon = 3
}

/// <summary>
/// 音量空間距離衰減曲線模型。
/// </summary>
public enum AttenuationCurveKind : byte
{
    /// <summary>線性衰減：V = 1 - t。</summary>
    Linear = 0,

    /// <summary>平滑 S 曲線（SmoothStep）：V = 1 - (3t² - 2t³)，無突變拐角。</summary>
    SmoothStep = 1,

    /// <summary>對數/物理近似衰減：近距離衰減迅速，遠距離平緩消退。</summary>
    Logarithmic = 2,

    /// <summary>指數快速衰減：V = (1 - t)²，適用強烈局部小音源（如火把劈啪）。</summary>
    Exponential = 3
}

/// <summary>
/// 音效分類屬性。
/// </summary>
public enum AudioCategory : byte
{
    /// <summary>全域底層環境音（風聲、天空空靈音）。</summary>
    AmbientGlobal = 0,

    /// <summary>區域地景氛圍（森林、平原、沼澤、雪原）。</summary>
    AmbientZone = 1,

    /// <summary>定點發聲源（營火、鐵砧、噴泉）。</summary>
    PointEmitter = 2,

    /// <summary>水文動態伴生音（河流、急流、瀑布、海浪）。</summary>
    Hydrology = 3,

    /// <summary>植被生態伴生音（密林風動、疏林、鳥鳴群）。</summary>
    Vegetation = 4,

    /// <summary>聚落與生產生活音（居民低語、市場喧囂）。</summary>
    Settlement = 5,

    /// <summary>動態天氣音（暴風雨雷鳴、冰雹砸地）。</summary>
    WeatherFx = 6
}

/// <summary>
/// 音效播放觸發模式。
/// </summary>
public enum SoundTriggerMode : byte
{
    /// <summary>連續無縫循環播放（如河流、風聲、營火）。</summary>
    ContinuousLoop = 0,

    /// <summary>隨機隨機間歇觸發（如布穀鳥、落雷、狼嚎、水滴）。</summary>
    RandomStochasticInterval = 1,

    /// <summary>時段條件過濾（僅白天或僅夜晚播放）。</summary>
    TimeOfDayConditional = 2
}

/// <summary>
/// 二維二維頂點坐標（世界空間 X 與 Z）。
/// </summary>
public readonly record struct SoundscapeVertex(float X, float Z);

/// <summary>
/// 原生音效預設或定義項。
/// </summary>
public sealed record SoundDef(
    string SoundId,
    string DisplayName,
    AudioCategory Category,
    SoundTriggerMode TriggerMode,
    float DefaultVolume = 1.0f,
    float DefaultInnerRadius = 200.0f,
    float DefaultOuterRadius = 800.0f,
    float MinIntervalSeconds = 4.0f,
    float MaxIntervalSeconds = 15.0f,
    bool DayOnly = false,
    bool NightOnly = false);

/// <summary>
/// 標記區域旗標位元。
/// </summary>
[Flags]
public enum SoundscapeZoneAttributes : uint
{
    None = 0,
    /// <summary>是否啟用循環播放。</summary>
    IsLooping = 1 << 0,
    /// <summary>區域當前是否啟用。</summary>
    IsActive = 1 << 1,
    /// <summary>是否由系統自動分析地形/水體/植被伴生生成。</summary>
    IsAutoGenerated = 1 << 2,
    /// <summary>是否計算地形地勢阻擋遮蔽（Occlusion）。</summary>
    OcclusionEnabled = 1 << 3,
    /// <summary>是否僅白天生效。</summary>
    DayOnly = 1 << 4,
    /// <summary>是否僅夜晚生效。</summary>
    NightOnly = 1 << 5
}

/// <summary>
/// 單一環境音效區域實體。
/// </summary>
public sealed class SoundscapeZone
{
    public Guid Id { get; init; } = Guid.NewGuid();
    public string Name { get; set; } = "New Soundscape Zone";
    public string SoundDefId { get; set; } = "Amb_Forest_Light";
    public SoundscapeShapeType ShapeType { get; set; } = SoundscapeShapeType.Circle;
    public AttenuationCurveKind AttenuationCurve { get; set; } = AttenuationCurveKind.SmoothStep;
    public AudioCategory Category { get; set; } = AudioCategory.AmbientZone;

    /// <summary>基礎音量（0.0 ~ 1.0）。</summary>
    public float BaseVolume { get; set; } = 1.0f;

    /// <summary>混音通道優先級（0 ~ 255，數值愈高愈不易被通道上限剔除）。</summary>
    public ushort Priority { get; set; } = 128;

    /// <summary>全音量無損半徑（自邊界向外距離小於等於此值時音量為 100%）。</summary>
    public float InnerRadius { get; set; } = 150.0f;

    /// <summary>外側衰減邊界半徑（超出此距離時音量為 0）。</summary>
    public float OuterRadius { get; set; } = 600.0f;

    /// <summary>世界中心坐標 X。</summary>
    public float CenterWorldX { get; set; }

    /// <summary>世界中心坐標 Y（高度）。</summary>
    public float CenterWorldY { get; set; }

    /// <summary>世界中心坐標 Z。</summary>
    public float CenterWorldZ { get; set; }

    /// <summary>
    /// 形狀參數 A：
    /// Circle: 核心基礎半徑；
    /// OrientedRectangle: 半寬 (HalfWidth)。
    /// </summary>
    public float ParamA { get; set; } = 200.0f;

    /// <summary>
    /// 形狀參數 B：
    /// OrientedRectangle: 半長 (HalfHeight)。
    /// </summary>
    public float ParamB { get; set; } = 200.0f;

    /// <summary>
    /// 定向旋轉角度（度數，OrientedRectangle 朝向）。
    /// </summary>
    public float ParamAngleDeg { get; set; }

    /// <summary>
    /// 凸多邊形頂點清單（以世界坐標 X, Z 順時針或逆時針排序）。
    /// </summary>
    public List<SoundscapeVertex> PolygonVertices { get; init; } = [];

    /// <summary>音效區域狀態屬性。</summary>
    public SoundscapeZoneAttributes Attributes { get; set; } = SoundscapeZoneAttributes.IsLooping | SoundscapeZoneAttributes.IsActive;

    /// <summary>相容別名 Flags 屬性。</summary>
    public SoundscapeZoneAttributes Flags { get => Attributes; set => Attributes = value; }

    /// <summary>建立深層副本。</summary>
    public SoundscapeZone Clone()
    {
        return new SoundscapeZone
        {
            Id = Id,
            Name = Name,
            SoundDefId = SoundDefId,
            ShapeType = ShapeType,
            AttenuationCurve = AttenuationCurve,
            Category = Category,
            BaseVolume = BaseVolume,
            Priority = Priority,
            InnerRadius = InnerRadius,
            OuterRadius = OuterRadius,
            CenterWorldX = CenterWorldX,
            CenterWorldY = CenterWorldY,
            CenterWorldZ = CenterWorldZ,
            ParamA = ParamA,
            ParamB = ParamB,
            ParamAngleDeg = ParamAngleDeg,
            PolygonVertices = new List<SoundscapeVertex>(PolygonVertices),
            Attributes = Attributes
        };
    }
}

/// <summary>
/// 整張地圖的音效區域狀態快照。
/// </summary>
public sealed record SoundscapeSnapshot(
    string GlobalAmbienceId,
    float GlobalAmbienceVolume,
    IReadOnlyList<SoundscapeZone> Zones);

/// <summary>
/// 供 2D/3D 編輯畫布渲染用的 Audio Gizmo 幾何圖元資料。
/// </summary>
public sealed record AudioGizmoRepresentation(
    Guid ZoneId,
    string Name,
    string SoundDefId,
    AudioCategory Category,
    SoundscapeShapeType ShapeType,
    float CenterX,
    float CenterY,
    float CenterZ,
    float InnerRadius,
    float OuterRadius,
    IReadOnlyList<SoundscapeVertex> CoreBoundary,
    IReadOnlyList<SoundscapeVertex> FalloffBoundary,
    uint ColorRgba,
    bool IsSelected);

/// <summary>
/// 單一發聲源在虛擬聆聽者位置的即時音訊計算值。
/// </summary>
public sealed record AudibleChannelEvaluation(
    Guid ZoneId,
    string SoundDefId,
    AudioCategory Category,
    float DistanceToZone,
    float FalloffFactor,
    float EffectiveVolume,
    float PanningLeft,
    float PanningRight,
    float AzimuthDegrees,
    ushort Priority);

/// <summary>
/// 虛擬聆聽者在指定空間點的音場混合評估結果。
/// </summary>
public sealed record SoundscapeMixResult(
    float ListenerX,
    float ListenerY,
    float ListenerZ,
    float ListenerYawDeg,
    float TotalPerceivedVolume,
    float MasterLeftVolume,
    float MasterRightVolume,
    int ActiveAudibleCount,
    bool ChannelBudgetExceeded,
    IReadOnlyList<AudibleChannelEvaluation> Channels);
