<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="PngWriter.cs" />
    <Compile Include="../../../src.MapEditor.Modules/NativeAssets/NativeShadow*.cs" Link="%(Filename)%(Extension)" />
  </ItemGroup>
</Project>