import struct
import sys
import os

def rva_to_offset(rva, sections):
    for sec in sections:
        if sec['va'] <= rva < sec['va'] + sec['vsize']:
            return rva - sec['va'] + sec['ptr']
    return 0

def read_cstr(data, offset):
    end = data.find(b'\x00', offset)
    if end == -1: return ""
    return data[offset:end].decode('ascii')

def main():
    dll_path = r"C:\Windows\SysWOW64\winmm.dll"
    with open(dll_path, "rb") as f:
        data = f.read()

    e_lfanew = struct.unpack_from("<I", data, 0x3C)[0]
    pe_sig = data[e_lfanew:e_lfanew+4]
    if pe_sig != b"PE\0\0":
        print("Not a PE file")
        return

    num_sections = struct.unpack_from("<H", data, e_lfanew + 4 + 2)[0]
    size_opt_header = struct.unpack_from("<H", data, e_lfanew + 4 + 16)[0]

    magic = struct.unpack_from("<H", data, e_lfanew + 24)[0]
    if magic == 0x10b: # 32-bit
        export_rva = struct.unpack_from("<I", data, e_lfanew + 24 + 96)[0]
    elif magic == 0x20b: # 64-bit
        export_rva = struct.unpack_from("<I", data, e_lfanew + 24 + 112)[0]
    else:
        print("Unknown magic")
        return

    if export_rva == 0:
        print("No exports")
        return

    sections_offset = e_lfanew + 24 + size_opt_header
    sections = []
    for i in range(num_sections):
        sec_off = sections_offset + i * 40
        vsize = struct.unpack_from("<I", data, sec_off + 8)[0]
        va = struct.unpack_from("<I", data, sec_off + 12)[0]
        raw_size = struct.unpack_from("<I", data, sec_off + 16)[0]
        ptr = struct.unpack_from("<I", data, sec_off + 20)[0]
        sections.append({'va': va, 'vsize': vsize, 'ptr': ptr})

    export_off = rva_to_offset(export_rva, sections)
    ordinal_base = struct.unpack_from("<I", data, export_off + 16)[0]
    num_funcs = struct.unpack_from("<I", data, export_off + 20)[0]
    num_names = struct.unpack_from("<I", data, export_off + 24)[0]
    func_rva = struct.unpack_from("<I", data, export_off + 28)[0]
    name_rva = struct.unpack_from("<I", data, export_off + 32)[0]
    ord_rva = struct.unpack_from("<I", data, export_off + 36)[0]

    func_off = rva_to_offset(func_rva, sections)
    name_off = rva_to_offset(name_rva, sections)
    ord_off = rva_to_offset(ord_rva, sections)

    name_to_ord = {}
    for i in range(num_names):
        n_rva = struct.unpack_from("<I", data, name_off + i * 4)[0]
        n_off = rva_to_offset(n_rva, sections)
        name = read_cstr(data, n_off)
        ordinal_index = struct.unpack_from("<H", data, ord_off + i * 2)[0]
        name_to_ord[ordinal_index] = name

    exports = []
    for i in range(num_funcs):
        func_addr_rva = struct.unpack_from("<I", data, func_off + i * 4)[0]
        if func_addr_rva == 0:
            continue
        ordinal = ordinal_base + i
        if i in name_to_ord:
            exports.append({"ordinal": ordinal, "name": name_to_ord[i]})
        else:
            exports.append({"ordinal": ordinal, "name": None})

    exports.sort(key=lambda x: x['ordinal'])

    # Write argm_trace.def
    def_path = os.path.join(os.path.dirname(__file__), "argm_trace.def")
    with open(def_path, "w", newline='\n') as f:
        f.write("; Export table for the winmm.dll proxy. LIBRARY name matches the DLL's runtime\n")
        f.write("; file name (winmm.dll). Generated by generate_exports.py.\n")
        f.write("LIBRARY winmm\n")
        f.write("EXPORTS\n")
        for exp in exports:
            if exp['name'] is None:
                f.write(f"    Thunk_Ordinal{exp['ordinal']} @{exp['ordinal']} NONAME\n")
            else:
                f.write(f"    {exp['name']} = Thunk_{exp['name']} @{exp['ordinal']}\n")

    # Write src/winmm_exports.inc
    inc_path = os.path.join(os.path.dirname(__file__), "src", "winmm_exports.inc")
    with open(inc_path, "w", newline='\n') as f:
        f.write("// Generated by generate_exports.py.\n")
        f.write("#define WINMM_EXPORTS(X) \\\n")
        named_exports = [exp for exp in exports if exp['name'] is not None]
        for i, exp in enumerate(named_exports):
            suffix = " \\" if i < len(named_exports) - 1 else ""
            f.write(f"    X({exp['name']}){suffix}\n")

if __name__ == '__main__':
    main()
