using System;
using System.Collections.Generic;

namespace AgainstRomeModifier {
    public enum Language {
        TraditionalChinese,
        English
    }

    public static class Loc {
        public static Language CurrentLanguage { get; set; } = Language.TraditionalChinese;

        public static string Get(string key) {
            if (CurrentLanguage == Language.English) {
                return En.TryGetValue(key, out var valEn) ? valEn : key;
            }
            return Zh.TryGetValue(key, out var valZh) ? valZh : key;
        }

        public static string GetUnitName(string key) {
            if (CurrentLanguage == Language.English) {
                return EnUnitNames.TryGetValue(key, out var valEn) ? valEn : (TroopConfig.UnitNames.TryGetValue(key, out var zhVal) ? zhVal : key);
            }
            return TroopConfig.UnitNames.TryGetValue(key, out var valZh) ? valZh : key;
        }

        public static string GetUnitType(string utype) {
            if (CurrentLanguage == Language.English) {
                switch (utype) {
                    case "melee_inf": return "Melee Infantry";
                    case "ranged_inf": return "Ranged Infantry";
                    case "ranged_cav": return "Ranged Cavalry";
                    case "hybrid_inf": return "Hybrid Infantry";
                    case "cav": return "Cavalry";
                    case "leader_melee": return "Leader (Melee)";
                    case "leader_cav": return "Leader (Cavalry)";
                    case "priest": return "Priest";
                    case "siege": return "Siege Weapon";
                    default: return "Unknown";
                }
            }
            switch (utype) {
                case "melee_inf": return "近戰步兵";
                case "ranged_inf":
                case "ranged_cav": return "遠程部隊";
                case "hybrid_inf": return "混合步兵";
                case "cav": return "騎兵部隊";
                case "leader_melee":
                case "leader_cav": return "領袖";
                case "priest": return "祭司";
                case "siege": return "攻城武器";
                default: return "未知";
            }
        }

        public static string GetStyleText(string style) {
            if (CurrentLanguage == Language.English) {
                switch (style) {
                    case "shield": return "Shielded";
                    case "two_handed": return "Two-Handed";
                    case "dual_wield": return "Dual-Wield";
                    case "ranged": return "Ranged";
                    default: return "None";
                }
            }
            switch (style) {
                case "shield": return "持盾";
                case "two_handed": return "雙手武器";
                case "dual_wield": return "雙持武器";
                case "ranged": return "遠程";
                default: return "無";
            }
        }

        public static string GetTierText(string tier) {
            if (CurrentLanguage == Language.English) {
                switch (tier) {
                    case "low": return "Low Tier";
                    case "mid": return "Mid Tier";
                    case "high": return "High Tier";
                    case "ace": return "Ace";
                    case "leader": return "Leader";
                    case "siege": return "Siege";
                    default: return "Unknown";
                }
            }
            switch (tier) {
                case "low": return "低階";
                case "mid": return "中階";
                case "high": return "高階";
                case "ace": return "王牌";
                case "leader": return "領袖";
                case "siege": return "攻城武器";
                default: return "未知";
            }
        }

        public static string GetFactionName(string faction) {
            if (CurrentLanguage == Language.English) {
                return faction;
            }
            switch (faction) {
                case "Roman": return "羅馬";
                case "Teuton": return "條頓";
                case "Celt": return "塞爾特";
                case "Hun": return "匈奴";
                default: return faction;
            }
        }

        private static readonly Dictionary<string, string> EnUnitNames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) {
            {"FigRomAnf00_Anfuehrer", "Roman Leader"},
            {"FigRomInf00_Lanze_Schild", "Roman Light Infantry"},
            {"FigRomInf01_Schwert_Schild", "Roman Sword & Shieldman"},
            {"FigRomKav00_Schwert_Schild", "Roman Assault Cavalry"},
            {"FigRomSch00_Speer_Schild", "Roman Heavy Infantry"},
            {"FigRomSch01_Bogen", "Roman Archer"},
            {"FigGerAnf00_Anfuehrer", "Teuton Leader"},
            {"FigGerInf00_Hammer_Schild", "Teuton Mace & Shieldman"},
            {"FigGerInf01_Schwert", "Teuton Swordsman"},
            {"FigGerInf02_Zweihandaxt", "Teuton Two-Handed Axeman"},
            {"FigGerInf03_Doppelhammer", "Teuton Dual Hammerer"},
            {"FigGerKav00_Schwert_Schild", "Teuton Cavalry"},
            {"FigGerPri00_Priester", "Teuton Priest"},
            {"FigGerSch00_Speer", "Teuton Spearman"},
            {"FigGerSch01_Axt_Schild", "Teuton Ax & Shieldman"},
            {"FigKelAnf00_Anfuehrer", "Celt Leader"},
            {"FigKelInf00_Schwert", "Celt Swordsman"},
            {"FigKelInf01_Lanze", "Celt Spearman"},
            {"FigKelInf02_Doppelschwert", "Celt Heavy Infantry"},
            {"FigKelKav00_Lanze_Schild", "Celt Lancer"},
            {"FigKelPri00_Priester", "Celt Priest"},
            {"FigKelSch00_Bogen", "Celt Archer"},
            {"FigKelSch01_Schleuder", "Celt Slinger"},
            {"FigKelSch02_Schwere_Schleuder", "Celt Heavy Slinger"},
            {"FigHunAnf00_Anfuehrer", "Hun Leader"},
            {"FigHunInf00_Keule", "Hun Clubman"},
            {"FigHunInf01_Schwert_Schild", "Hun Sword & Shieldman"},
            {"FigHunKav00_Schwert_Schild", "Hun Light Cavalry"},
            {"FigHunKav01_Bogen", "Hun Archer Cavalry"},
            {"FigHunKav02_Lanze_Schild", "Hun Heavy Cavalry"},
            {"FigHunKav03_Geisterreiter", "Hun Ghost Warrior"},
            {"FigHunPri00_Priester", "Hun Priest"},
            {"FigHunSch00_Bogen", "Hun Archer"},
            {"FigGerArt00_Katapult", "Teuton Catapult"},
            {"FigGerArt00_Katapult_Aufbau", "Teuton Deployed Catapult"},
            {"FigRomArt00_Speerschleuder", "Roman Ballista"},
            {"FigRomArt00_Speerschleuder_Auf", "Roman Deployed Ballista"},
            {"FigRomArt01_Katapult", "Roman Catapult"},
            {"FigRomArt01_Katapult_Aufbau", "Roman Deployed Catapult"},
            {"FigKelArt00_Speerschleuder", "Celt Ballista"},
            {"FigKelArt00_Speerschleuder_A", "Celt Deployed Ballista"},
            {"FigKelArt01_Katapult", "Celt Catapult"},
            {"FigKelArt01_Katapult_Aufbau", "Celt Deployed Catapult"}
        };

        private static readonly Dictionary<string, string> Zh = new Dictionary<string, string> {
            // UI elements
            { "NavSystem", "主控制台" },
            { "NavDefaultStats", "自訂兵種屬性" },
            { "NavCurrentStats", "當前兵種數值" },
            { "NavSaveManager", "遊戲存檔管理" },
            { "NavMapManager", "地圖管理" },
            { "NavDoc", "修改技術文件" },
            { "NavSkills", "技能屬性修改" },
            { "SkillsHeading", "技能與首領榮譽屬性設定" },
            { "SkillsSubtitle", "自訂部隊主動技能倍率、首領被動特殊技能，以及首領榮譽成長與光環屬性。" },
            { "ColSkillName", "技能與項目" },
            { "ColSkillValue", "當前數值" },
            { "ColSkillDefault", "原版預設值" },
            { "ColGloryLeader", "首領" },
            { "ColGloryAwStuf", "攻擊成長" },
            { "ColGloryVwStuf", "防禦成長" },
            { "ColGloryDamStuf", "傷害成長" },
            { "ColGloryMoraleBonus", "士氣光環" },
            { "ColGloryMoraleTime", "光環時間(ms)" },
            { "ColGloryMaxRuhm", "滿級榮耀" },
            { "GrpGeneralSkills", "部隊與首領特殊技能 (cl_epara.ini & cl_script.ini)" },
            { "GrpLeaderGlory", "首領榮譽升級與士氣光環屬性 (objdef.dau)" },
            { "MainTitle", "AGAINST ROME MODIFIER PRO" },
            { "SystemHeading", "修改器控制中心" },
            { "SystemSubtitle", "選擇要啟用的功能，確認遊戲路徑後再執行修改。" },
            { "NumericTitle", "系統與相容性設定" },
            { "MaxPopulation", "最大人口上限 (1600)" },
            { "RomanEndless", "無盡模式羅馬陣營" },
            { "FastCiviProduction", "村民生產速度最快" },
            { "FocusLoss", "視窗失焦不自動暫停" },
            { "GameSpeedLabel", "整體遊戲運行 10 倍加速" },
            { "GameSpeedOff", "原版（不加速）" },
            { "GameSpeedItem", "{0}× 加速" },
            { "ModSkillsAndGlory", "套用自訂首領與單位技能" },
            { "ToEng", "強制英文語系" },
            { "ExperimentalTitle", "實驗性功能" },
            { "GeneralSkills", "將軍特殊技能強化" },
            { "LeaderGlory", "首領榮譽與士氣光環增強" },
            { "EnableAll", "所有功能開啟" },
            { "DisableAll", "所有功能關閉" },
            { "SwitchesTitle", "資源與戰鬥修改" },
            { "BuildTitle", "建設與人口設定" },
            { "FreeProd", "建造與生產免費" },
            { "FreeUpgrade", "科技與升級免費" },
            { "NoSpellCost", "祭司與賢者無限法力" },
            { "NoSpellAltar", "法術免除祭壇需求" },
            { "SpellDamage5x", "法術傷害提升 5 倍" },
            { "SpellHealing10x", "治療術提升 10 倍" },
            { "SpellResurrection", "法師復活術強化" },
            { "InfiniteMorale", "部隊無限士氣" },
            { "HousingCapacity20x", "人口建築容量提升" },
            { "StorageCapacity10x", "主堡與倉庫容量提升" },
            { "HqHp10x", "主堡生命值提升" },
            { "FastBuildUpgradeRepair", "建築建造與維修加速" },
            { "FoodHealing10x", "待機回血速度提升" },
            { "CiviProduce20", "住宅帳篷一次生產 20 人" },
            { "AiCardTitle", "AI 終極戰爭模式 (無盡重生)" },
            { "AiM1", "增援兵團擴軍" },
            { "AiM2", "加速電腦增援" },
            { "AiM3", "加速敗亡清理" },
            { "AiM4", "必定建立聚落" },
            { "AiM5", "提供開局資源" },
            { "AiM6", "提升守軍數量" },
            { "DgVoodoo", "啟用圖形相容修補" },
            { "VillageBuildRange", "全地圖自由建設" },
            { "GamePath", "遊戲路徑:" },
            { "Browse", "瀏覽..." },
            { "LoadCurrent", "讀取現有設定" },
            { "Restore", "恢復原版" },
            { "Apply", "執行修改" },
            { "StartGame", "啟動遊戲" },
            { "RestoreAll", "全部還原" },
            { "RestoreStats", "僅還原兵種屬性" },
            { "RestoreCompat", "僅還原相容性修正" },
            { "RestoreLang", "僅還原語系設定" },
            { "DefaultStatsTitle", "自訂兵種屬性對比 (無自訂加成)" },
            { "EnableBalance", "啟用自訂兵種屬性平衡與陣營特色" },
            { "TroopTemplateLabel", "選擇範本:" },
            { "TroopTemplateSelect", "(請選擇範本)" },
            { "TroopTemplateBalanced", "修改器內建平衡" },
            { "BtnTroopPreset", "修改兵種檔案" },
            { "TroopPresetDefault", "屬性檔案：預設範本" },
            { "TroopPresetManual", "屬性檔案：自訂配置 (手動)" },
            { "TroopPresetFile", "屬性檔案：{0}" },
            { "TroopPresetLoaded", "屬性檔案：設定檔載入 ({0})" },
            { "CurrentStatsTitle", "當前兵種數值 (原版與當前對比)" },
            { "GameSavesTitle", "遊戲中存檔列表" },
            { "BackupsTitle", "備份歷史列表" },
            { "DetailTitle", "存檔詳細與預覽" },
            { "BackupSave", "備份此存檔" },
            { "DeleteSave", "刪除此存檔" },
            { "Refresh", "重新整理" },
            { "RestoreBackup", "還原此備份" },
            { "DeleteBackup", "刪除此備份" },
            { "LanguageLabel", "修改器語系 / Language" },
            { "LangZhButton", "繁體中文" },
            { "LangEnButton", "English" },

            // Headers Default Grid
            { "HeaderName", "兵種名稱" },
            { "HeaderIcon", "圖示" },
            { "HeaderType", "部隊類型" },
            { "HeaderStyle", "裝備分類" },
            { "HeaderHp", "生命值" },
            { "HeaderMeleeDmg", "近戰傷害" },
            { "HeaderRangedDmg", "遠程傷害" },
            { "HeaderMeleeRelt", "近戰冷卻" },
            { "HeaderRangedRelt", "遠程冷卻" },
            { "HeaderVw", "防禦力" },
            { "HeaderAw", "戰鬥力" },
            { "HeaderSpeed", "移動速度" },
            { "HeaderSight", "視野" },
            { "HeaderRange", "射程/技能距離" },
            { "HeaderSpellRadius", "法術半徑" },
            { "HeaderTier", "階級" },

            // Headers Current Grid
            { "HeaderHpComp", "生命值對比" },
            { "HeaderMeleeDmgComp", "近戰傷害對比" },
            { "HeaderRangedDmgComp", "遠程傷害對比" },
            { "HeaderMeleeReltComp", "近戰冷卻對比" },
            { "HeaderRangedReltComp", "遠程冷卻對比" },
            { "HeaderVwComp", "防禦對比" },
            { "HeaderAwComp", "戰鬥對比" },
            { "HeaderSpeedComp", "移動速度對比" },
            { "HeaderSightComp", "視野對比" },
            { "HeaderRangeComp", "射程對比" },
            { "HeaderSpellRadiusComp", "法術半徑對比" },

            // Save grid specific headers
            { "HeaderFolder", "資料夾" },
            { "HeaderSaveTitle", "存檔標題" },
            { "HeaderLevel", "原版關卡" },
            { "HeaderTime", "存檔時間" },
            { "HeaderBackupFile", "備份檔名" },
            { "HeaderBackupTime", "備份時間" },
            { "HeaderOrigFolder", "原資料夾" },

            // Tabs
            { "TabRoman", " 羅馬 " },
            { "TabTeuton", " 條頓 " },
            { "TabCelt", " 塞爾特 " },
            { "TabHun", " 匈奴 " },

            // Dialog / Log / Message titles
            { "TitlePathError", "路徑錯誤" },
            { "TitleConfirm", "確認執行" },
            { "TitleSuccess", "成功" },
            { "TitleError", "錯誤" },
            { "TitleWarning", "確認覆蓋" },
            { "TitleConfirmDelete", "確認刪除" },
            { "TitleTips", "提示" },

            // Dialog / Log / Message strings
            { "LogConstructCompleted", "修改器視窗建構完成，開始載入資料..." },
            { "LogLoadIconFailed", "載入圖示失敗: " },
            { "LogDefaultStatsLoaded", "自訂兵種屬性載入完成，共 {0} 筆資料。" },
            { "LogDefaultStatsLoadError", "載入自訂屬性數據錯誤: " },
            { "LogBalanceToggled", "自訂兵種屬性平衡與陣營特色已{0}。" },
            { "LogReadCurrent", "正在讀取現有設定..." },
            { "LogReadCurrentDone", "現有屬性設定讀取完成，共 {0} 筆比對資料。" },
            { "LogPresetImportError", "讀取現有設定失敗: " },
            { "LogBrowseTitle", "請選擇《羅馬的榮耀》(Against Rome) 遊戲安裝目錄" },
            { "MsgSelectGameDir", "請先設定正確的遊戲路徑。" },
            { "MsgWrongGameDir", "設定的目錄不包含遊戲主程式 Against_Rome.exe，請重新選擇正確的安裝路徑。" },
            { "MsgConfirmApply", "確定要套用所有修改嗎？\n此操作將覆蓋遊戲檔案。" },
            { "MsgApplySuccess", "修改成功套用！" },
            { "MsgApplyFailed", "修改失敗: " },
            { "MsgRestoreAllSuccess", "已成功恢復全部原版設定！" },
            { "MsgRestoreStatsSuccess", "已成功恢復兵種屬性設定！" },
            { "MsgRestoreCompatSuccess", "已成功恢復相容性設定！" },
            { "MsgRestoreLangSuccess", "已成功恢復語言設定！" },
            { "MsgRestoreFailed", "還原失敗: " },
            { "MsgExeNotFound", "在遊戲目錄中找不到 Against_Rome.exe。" },
            { "MsgLaunchFailed", "啟動遊戲失敗: " },
            { "LogStartApply", "開始套用修改..." },
            { "LogApplyAllSuccess", "所有修改已成功套用！" },
            { "LogStartRestoreAll", "開始恢復全部原版設定..." },
            { "LogRestoreAllDone", "已成功恢復全部原版設定。" },
            { "LogStartRestoreStats", "開始恢復兵種屬性原版設定..." },
            { "LogRestoreStatsDone", "已成功恢復兵種屬性設定。" },
            { "LogStartRestoreCompat", "開始恢復相容性原版設定..." },
            { "LogRestoreCompatDone", "已成功恢復相容性設定。" },
            { "LogStartRestoreLang", "開始恢復語言原版設定..." },
            { "LogRestoreLangDone", "已成功恢復語言設定。" },
            { "LogGameStarted", "遊戲已成功啟動。" },
            { "LogGamePathNotSetIcon", "遊戲路徑未設定或不存在，無法載入兵種圖示。" },
            { "LogGuiDatNotFound", "找不到 gui.dat，無法載入兵種圖示。" },
            { "LogIconIniNotFound", "記憶體備份中找不到 icon.ini，無法載入兵種圖示。" },
            { "LogObjdefNotFound", "記憶體備份中找不到 objdef.dau，無法載入自訂兵種屬性。" },
            { "LogNoObjdefForRead", "找不到任何 objdef.dau 檔案，無法讀取設定。" },
            { "LogSavePathNotSet", "遊戲路徑未設定，無法載入存檔。" },
            { "LogRefreshSavesFailed", "重新整理存檔列表失敗: " },
            { "SaveDetailGameSave", "存檔類型: 遊戲存檔\n\n資料夾: {0}\n\n存檔標題: {1}\n\n原版關卡: {2}\n\n存檔時間: {3}" },
            { "SaveDetailBackup", "存檔類型: 備份檔案\n\n備份檔名: {0}\n\n原資料夾: {1}\n\n存檔標題: {2}\n\n原版關卡: {3}\n\n備份時間: {4}" },
            { "MsgSelectBackup", "請先選擇要還原的備份。" },
            { "MsgCannotResolveOrigFolder", "無法判斷該備份的原資料夾，無法還原。" },
            { "MsgGamePathNotSet", "遊戲路徑未設定，無法還原。" },
            { "MsgConfirmOverwriteSave", "目標存檔資料夾 [{0}] 已存在，是否覆蓋？" },
            { "MsgRestoreBackupSuccess", "還原備份成功！" },
            { "MsgRestoreBackupFailed", "還原備份失敗: " },
            { "MsgSelectSaveToDelete", "請先選擇要刪除的存檔。" },
            { "MsgInvalidSaveDir", "無效的存檔目錄，操作已取消。" },
            { "MsgConfirmDeleteSave", "確定要永久刪除遊戲存檔 [{0}] 嗎？此操作不可還原！" },
            { "MsgDeleteSaveSuccess", "已刪除存檔！" },
            { "MsgDeleteSaveFailed", "刪除存檔失敗: " },
            { "MsgSelectBackupToDelete", "請先選擇要刪除的備份。" },
            { "MsgConfirmDeleteBackup", "確定要永久刪除備份檔案 [{0}] 嗎？" },
            { "MsgDeleteBackupSuccess", "已刪除備份！" },
            { "MsgDeleteBackupFailed", "刪除備份失敗: " },
            { "MsgSelectSaveToBackup", "請先選擇要備份的存檔。" },
            { "MsgNoOrigFolderToBackup", "找不到該存檔的原始資料夾。" },
            { "MsgBackupSaveSuccess", "備份存檔成功！" },
            { "MsgBackupSaveFailed", "備份存檔失敗: " },
            { "LogLoadTechDocFailed", "載入技術文件資源失敗: " },
            { "Unparsable", "無法解析" },
            { "Unknown", "未知" },
            { "LogBackupSaveSuccessDetail", "備份存檔成功: {0} -> {1}" },
            { "LogBackupSaveFailedDetail", "備份存檔失敗: " },
            { "LogRestoreBackupSuccessDetail", "還原備份成功: {0} -> {1}" },
            { "LogRestoreBackupCleanupFailed", "存檔已還原，但舊存檔暫存資料夾無法清除: " },
            { "LogRestoreBackupFailedDetail", "還原備份失敗: " },
            { "LogDeleteSaveSuccessDetail", "已刪除遊戲存檔: {0}" },
            { "LogDeleteSaveFailedDetail", "刪除存檔失敗: " },
            { "LogDeleteBackupSuccessDetail", "已刪除備份檔案: {0}" },
            { "LogDeleteBackupFailedDetail", "刪除備份失敗: " },
            { "FocusLossTip", "當你切換到桌面、瀏覽器或其他程式（Alt+Tab）時，遊戲不會強制暫停，而是繼續在背景流暢運行，非常適合掛網等待生產與建造！" },
            { "ModSkillsAndGloryTip", "啟用此選項以套用在「技能屬性修改」分頁中所設定的部隊技能、首領被動特殊技能，以及首領榮譽成長與光環數值。若未啟用，則寫入原版預設值。" },
            { "ToEngTip", "將遊戲內的介面、按鈕、地圖與核心文字切換為英文版。能有效解決老遊戲在現代 Windows 系統上的字型亂碼或切換語系時造成的遊戲卡死問題。" },
            { "DgVoodooTip", "安裝 dgVoodoo2 相容層（Direct3D8 轉換器）。能完美修復老遊戲在 Windows 10/11 上常見的畫面卡頓、幀率（FPS）極低、視窗化失敗或啟動黑屏等圖形相容性問題。" },
            { "GameSpeedTip", "全局縮放遊戲運作時脈。從生產、建造、移動到戰鬥和 AI 反應，通通同步加速 10 倍！掛機等待時極為實用！" },
            { "GeneralSkillsTip", "將所有將軍與首領的被動特殊技能數值大幅提升 5 倍。" },
            { "LeaderGloryTip", "將各陣營首領隨榮譽升級的攻擊成長、防禦成長、傷害成長與士氣光環數值提升 5 倍。" },
            { "RangedRange3x", "遠程單位射程提升 3 倍" },
            { "RangedRange3xTip", "將所有遠程步兵、遠程騎兵以及攻城武器的攻擊/射擊射程提升 3 倍，並內建命中修正：拋射物落點的傷害判定半徑加倍（近失彈也算命中）、對移動目標預判的隨機散布歸零，避免拉遠射程後打不中。敵我全陣營一體適用。" },
            { "LogRangedRange3xToggled", "遠程單位射程提升 3 倍已{0}。" },
            { "UnitMovementSpeed2x", "單位移動速度提升 2 倍" },
            { "UnitMovementSpeed2xTip", "將所有戰鬥單位（包括士兵、領袖、祭司）與平民單位（村民、馱馬）的移動速度提升 2 倍。" },
            { "LogUnitMovementSpeed2xToggled", "單位移動速度提升 2 倍已{0}。" },
{ "SpellEntireMap", "法師施法距離提升至全地圖" },
{ "SpellEntireMapTip", "將所有祭司施放神術與復活術的最大施法距離提升至全地圖；不改變法術命中半徑。" },
{ "LogSpellEntireMapToggled", "法師施法距離提升至全地圖已{0}。" },
{ "SpellRange3x", "法師法術範圍提升 3 倍" },
{ "SpellRange3xTip", "將法術的效果與命中範圍提升為原版的 3 倍；不改變祭司的施法距離。" },
{ "LogSpellRange3xToggled", "法師法術範圍提升 3 倍已{0}。" },
            { "ProjectileArcHeight", "拋射彈道增高 2 倍" },
            { "ProjectileArcHeightTip", "將箭矢、標槍與投石等拋射物的垂直初速與重力同步提升 2 倍：彈道弧頂增高為原本的 2 倍、更容易越過樹木與建築等障礙物，落點與飛行時間維持不變。敵我全陣營一體適用。" },
            { "RomanEndlessTip", "將五張無盡地圖的玩家陣營強制改為羅馬人。部族選擇畫面的三面旗都會進入羅馬，旗幟可能顯示未選中；選項內的部族切換仍可由玩家手動改回蠻族。羅馬依原版設計沒有祭司與榮耀技能樹；只影響新開局，舊存檔不變。" },
            { "FreeProdTip", "建造所有建築物、指派工匠進行維修，以及在營房等軍事設施生產所有村民、步兵與騎兵單位時，完全不需要消耗任何木材、食物或金錢資源！" },
            { "FreeUpgradeTip", "研究兵種陣型、升級軍事科技（攻擊、防禦），以及提升兵種屬性解鎖時，通通免費、不消耗任何資源，助你瞬間研發滿科技！" },
            { "NoSpellCostTip", "施放所有祭司、賢者及法師的主動法術與復活技能時，魔法值（MP）零消耗，讓你的法師能夠無冷卻限制、源源不絕地降下法術天罰！" },
            { "InfiniteMoraleTip", "所有戰鬥單位的士氣值永久鎖定為最大，且在遭受奇襲、以少敵多或戰局不利時絕對不會下降。你的部隊將展現無畏的鋼鐵意志，決不潰逃！" },
            { "BalanceTip", "啟用修改器為各個陣營（羅馬、條頓、塞爾特、匈奴）精心調校的內建平衡屬性檔，修復原版兵種過強或過弱的問題，強化各個陣營的戰術特色。" },
            { "NoSpellAltarTip", "解除高級法術的建造前置條件。即使你只有 1 個祭壇，也能直接使用原版需要建造 3~5 個祭壇才能解鎖的進階強力神術，大幅省下建造成本與空間。" },
            { "SpellDamage5xTip", "將所有陣營的主動攻擊與傷害型法術傷害值提升 5 倍。" },
            { "SpellHealing10xTip", "將塞爾特人等祭司的治療術（Spell1）效果提升 10 倍，快速回復部隊生命。" },
            { "SpellResurrectionTip", "塞爾特人的復活術效果改為滿血滿士氣復活，且男屍體復活為槍盾兵、女屍體復活為女雙劍士。" },
            { "MaxPopulationTip", "解除遊戲原版的人口限制，讓單局戰場內所有陣營的最大總人口上限大幅提升至 1600 人，體驗千人同屏大會戰！" },
            { "HousingCapacity20xTip", "帳篷、民房等所有增加人口容量的建築物，所提供的人口上限額度暴增為原版的 20 倍！只需建造少量民房，即可輕鬆支持千人大軍。" },
            { "StorageCapacity10xTip", "城鎮中心（主堡）、倉庫等儲存資源建築的容量上限增加 10 倍。讓你大舉收集木材、食物等資源時，不再擔心倉庫過早爆滿而中斷生產。" },
            { "HqHp10xTip", "各個陣營城鎮中心（主帳篷/大本營）的生命值上限提升 10 倍。大大增強主營防禦力，避免敵軍偷襲一波爆地，也大幅提供維修緩衝時間。" },
            { "FastCiviProductionTip", "讓城鎮中心生產或轉換村民（農民）的速度加快 10 倍，實現開局人口爆發，快速發展經濟。" },
            { "FastBuildUpgradeRepairTip", "所有建築物的起建建造速度、升級研發速度，以及工匠的修復維修速度同步提升 10 倍！眨眼之間即可將廢墟修復或建好宏偉城塞。" },
            { "FoodHealing10xTip", "當受傷的士兵或單位處於閒置/待機狀態（沒有進行戰鬥或移動）時，每次自動回復生命值的數值由原版 1 點提升至 10 點，療傷速度奇快。已確認此回血不消耗任何食物資源。" },
            { "CiviProduce20Tip", "住宅帳篷生產面板的男/女生產鈕，點一次由原版排入 1 名村民改為一次排入 20 名（會自動夾到剩餘居住容量，建議搭配「20 倍居住容量」）。此為主程式層的玩家專屬修改，不影響 AI 電腦村莊。" },
            { "VillageBuildRangeTip", "將各個村莊大本營的建造邊界（原版在地圖上限制建設的紅框限制）擴充至全地圖！您現在可以在地圖的任何角落、任何敵軍腹地前哨自由地建造防禦塔、民房或營房！" },
            { "AiM1Tip", "無盡模式：電腦 AI 的每波增援部隊規模、增援重建以及村莊日常招募的兵團，由原版少數人提升至每隊 20 人！大幅增強戰鬥張力。" },
            { "AiM2Tip", "無盡模式：縮短電腦的增援等待時間至 30 秒，並加速其召喚兵團的排程判定。電腦 AI 將如同蜂湧般源源不絕地派兵進攻，打造無盡攻防戰！" },
            { "AiM3Tip", "無盡模式：電腦 AI 聚落被摧毀或敗亡時，加快舊村莊與殘破城牆的背景逐筆確認與清除，並將非定居點的撤退剩餘期限縮短為 1 分鐘，防止地圖卡死殘留。" },
            { "AiM4Tip", "無盡模式：打破原版重生機率逐次遞減的限制，將野外電腦部落的重生率鎖定在 100%。只要部落被消滅，很快就會有新的部落聚落前來建營。" },
            { "AiM5Tip", "無盡模式：給予新生成的電腦 AI 聚落額外的主堡儲備資源。這能幫助電腦 AI 在開局時快速發展起步，提早招兵買馬。僅影響電腦，不會影響玩家。" },
            { "AiM6Tip", "無盡模式：將整張地圖上電腦 AI 守衛、巡邏隊與定居點防守的活躍隊伍數量上限從原版 4 隊提高到 40 隊，極大充實野外地圖的守禦兵力！" },

            // 服務層 (PatchEngine / BackupManager) 日誌訊息
            { "SvcLogPreApplyRestore", "正在套用前將相關檔案復原為乾淨狀態，以清除殘留修改..." },
            { "SvcLogFocusApplied", "已套用視窗失去焦點不暫停補丁。" },
            { "SvcLogFocusRestored", "已還原視窗失去焦點暫停設定。" },
            { "SvcLogVillageLegacyRestoreUnknown", "無法還原舊版村莊建造半徑補丁：主程式特徵碼不符合。" },
            { "SvcLogVillageLegacyRemoved", "已移除舊版村莊建造半徑補丁。" },
            { "SvcLogVillageApplyUnknown", "無法套用村莊建造半徑補丁：主程式特徵碼不符合。" },
            { "SvcLogVillageApplied", "已套用村莊建造範圍擴大補丁。" },
            { "SvcLogVillageRestored", "已還原村莊建造範圍設定。" },
            { "SvcLogAltarApplied", "已套用法術免祭壇需求補丁。" },
            { "SvcLogAltarRestored", "已還原法術祭壇需求設定。" },
            { "SvcLogGameSpeedUnknown", "偵測到未知的遊戲時脈常數，已略過遊戲加速補丁以免覆蓋未知版本。" },
            { "SvcLogGameSpeedApplied", "遊戲整體運行速度：{0}× 加速。" },
            { "SvcLogGameSpeedOriginal", "遊戲整體運行速度：原版（未加速）。" },
            { "SvcLogTeamDatApplied", "已修改所有地圖的 team.dat 人口上限為 {0} (共處理 {1} 個檔案)。" },
            { "SvcLogTeamDatRestored", "已將所有地圖的 team.dat 人口上限還原為原版。" },
            { "SvcLogTeamDatRoman", "已將 {0} 張無盡地圖 (team.dat) 的玩家陣營改為羅馬。" },
            { "SvcLogTeamDatRomanRestored", "已將無盡地圖的玩家陣營還原為原版。" },
            { "SvcLogRomanEndlessExeApplied", "已將無盡模式部族選擇強制設為羅馬。" },
            { "SvcLogRomanEndlessExeRestored", "已還原無盡模式的原版部族選擇。" },
            { "SvcLogCiviProduce20Applied", "已將住宅帳篷生產鈕改為點一次 +20。" },
            { "SvcLogCiviProduce20Restored", "已還原住宅帳篷生產鈕為點一次 +1。" },
            { "SvcLogRomanEndlessExeUnknown", "無法辨識無盡模式羅馬陣營的 EXE 特徵碼，已保留主程式原狀。" },
            { "SvcLogRomanEndlessMismatch", "警告：無盡模式羅馬陣營的 EXE 與 team.dat 狀態不一致；介面狀態以 EXE 為準。" },
            { "SvcLogLeaderScriptMigrated", "已移除會造成戰鬥閃退的舊版首領榮耀腳本，並以原版 ak_anfuehrer.bci 重建。" },
            { "SvcLogLangApplied", "已成功套用英文介面與地圖語言包。" },
            { "SvcLogLangRestored", "已將英文介面與地圖語言包還原為原版。" },
            { "SvcLogDgvInstalled", "已成功安裝與設定 dgVoodoo2 ({0}) 繪圖轉譯器。" },
            { "SvcLogDgvNotManaged", "偵測到遊戲目錄中存在非本修改器部署的 dgVoodoo2 相關元件，為保護使用者資產將不主動進行刪除；若要乾淨卸載，請手動刪除遊戲目錄下的 DDraw.dll, D3D8.dll, dgVoodooCpl.exe。" },
            { "SvcLogDgvPreserved", "dgVoodoo2 託管設定檔 {0} 的雜湊值已變更，將予以保留不刪除。" },
            { "SvcLogDgvRemoved", "已成功移除 dgVoodoo2 所有受託管檔案。" },
            { "SvcLogRestoredFile", "已還原: {0}" },
            { "SvcLogRestoredPopulation", "已還原人口上限: {0}" },
            { "SvcLogDetectFailed", "[偵測] {0} 狀態偵測失敗，該群組選項將顯示為未勾選: {1}" },
            { "SvcLogBackupLoadedEmbedded", "已載入內嵌 Backup.zip 備份資料。" },
            { "SvcLogBackupLoadedLocal", "已載入程式目錄中的 Backup.zip 備份資料。" },
            { "SvcLogBackupMissing", "找不到內嵌或本機 Backup.zip；請選擇合法的遊戲安裝目錄，程式會從該目錄建立本機記憶體備份。" },
            { "SvcLogEparaHealed", "已使用修改器內建乾淨預設值修復記憶體備份項目: SYSTEM/cl_epara.ini" },
            { "SvcLogEparaHealFailed", "修復記憶體備份項目 SYSTEM/cl_epara.ini 失敗: {0}" },
            { "SvcLogEparaBuildFailed", "以內建預設值建立 SYSTEM/cl_epara.ini 備份失敗: {0}" },
            { "SvcLogAutoHealed", "已從遊戲目錄自動修復缺少之記憶體備份項目: {0}" },
            { "SvcLogAutoHealFailed", "自動修復記憶體備份項目 {0} 失敗: {1}" },
            { "SvcLogTeamDatHealed", "已從遊戲目錄自動修復地圖團隊備份項目 (team.dat)。" },
            { "SvcLogTeamDatHealFailed", "自動修復地圖 team.dat 備份失敗: {0}" },
            { "SvcLogBackupIncomplete", "備份來源缺少必要檔案，修改與還原功能可能無法安全執行:" },
            { "SvcLogBackupFromGameDir", "已成功從指定遊戲目錄建立乾淨記憶體備份。" }
        };

        private static readonly Dictionary<string, string> En = new Dictionary<string, string> {
            // UI elements
            { "NavSystem", "Main Console" },
            { "NavDefaultStats", "Custom Unit Stats" },
            { "NavCurrentStats", "Current Unit Stats" },
            { "NavSaveManager", "Save Manager" },
            { "NavMapManager", "Map Manager" },
            { "NavDoc", "Technical Doc" },
            { "NavSkills", "Skill Modifiers" },
            { "SkillsHeading", "Skill & Leader Glory Settings" },
            { "SkillsSubtitle", "Customize combat skill multipliers, chief special abilities, and leaders' glory scaling stats." },
            { "ColSkillName", "Skill / Attribute Item" },
            { "ColSkillValue", "Current Value" },
            { "ColSkillDefault", "Default Value" },
            { "ColGloryLeader", "Leader" },
            { "ColGloryAwStuf", "ATK Grow" },
            { "ColGloryVwStuf", "DEF Grow" },
            { "ColGloryDamStuf", "DMG Grow" },
            { "ColGloryMoraleBonus", "Aura Morale" },
            { "ColGloryMoraleTime", "Aura Time(ms)" },
            { "ColGloryMaxRuhm", "Max Glory" },
            { "GrpGeneralSkills", "Combat Skill & Tribe Ability Factors (cl_epara.ini & cl_script.ini)" },
            { "GrpLeaderGlory", "Chief Glory Scaling & Morale Aura (objdef.dau)" },
            { "MainTitle", "AGAINST ROME MODIFIER PRO" },
            { "SystemHeading", "Modifier Control Center" },
            { "SystemSubtitle", "Choose the features to enable, verify the game path, then apply the changes." },
            { "NumericTitle", "System & Compatibility Settings" },
            { "MaxPopulation", "Maximum Population Limit (1600)" },
            { "RomanEndless", "Play as Romans in Endless Mode" },
            { "FastCiviProduction", "Fastest Villager Production (10x)" },
            { "FocusLoss", "Run in Background (No Auto-Pause)" },
            { "GameSpeedLabel", "Overall Game Speed (10x Acceleration)" },
            { "GameSpeedOff", "Original (1x)" },
            { "GameSpeedItem", "{0}x Speed" },
            { "ModSkillsAndGlory", "Apply Custom Leader & Unit Skills" },
            { "ToEng", "Force English Language" },
            { "ExperimentalTitle", "Experimental Features" },
            { "GeneralSkills", "5x General Special Skills" },
            { "LeaderGlory", "Leader Glory & Morale Aura Buff" },
            { "EnableAll", "Enable All" },
            { "DisableAll", "Disable All" },
            { "SwitchesTitle", "Resource & Combat Upgrades" },
            { "BuildTitle", "Build & Population Settings" },
            { "FreeProd", "Free Construction, Repair & Unit Production" },
            { "FreeUpgrade", "Free Formations, Research & Upgrades" },
            { "NoSpellCost", "No Spell Cost for Priests & Druids" },
            { "NoSpellAltar", "No Spell Altar Requirements" },
            { "SpellDamage5x", "5x Spell Damage" },
            { "SpellHealing10x", "10x Healing Spell" },
            { "SpellResurrection", "Enhanced Resurrection" },
            { "InfiniteMorale", "Infinite Morale" },
            { "HousingCapacity20x", "20x Capacity for All Population Buildings" },
            { "StorageCapacity10x", "10x Storage Capacity for Town Halls & Warehouses" },
            { "HqHp10x", "10x HP for Town Halls" },
            { "FastBuildUpgradeRepair", "10x Faster Building Construction, Upgrade & Repair" },
            { "FoodHealing10x", "10x Idle HP Regeneration" },
            { "CiviProduce20", "Residential Tent: +20 Civilians Per Click" },
            { "AiCardTitle", "AI Ultimate (Endless)" },
            { "AiM1", "Reinf. Size (20/unit)" },
            { "AiM2", "Accelerated Reinf." },
            { "AiM3", "Fast Defeat Recovery" },
            { "AiM4", "Guaranteed Spawn" },
            { "AiM5", "AI Starting Resources" },
            { "AiM6", "Increase Garrison Size" },
            { "DgVoodoo", "Enable dgVoodoo2 Wrapper" },
            { "VillageBuildRange", "Village Build / Red-Frame Range (Entire Map)" },
            { "GamePath", "Game Path:" },
            { "Browse", "Browse..." },
            { "LoadCurrent", "Load Current" },
            { "Restore", "Restore Original" },
            { "Apply", "Apply Changes" },
            { "StartGame", "Launch Game" },
            { "RestoreAll", "Restore All" },
            { "RestoreStats", "Restore Stats Only" },
            { "RestoreCompat", "Restore Compatibility Only" },
            { "RestoreLang", "Restore Language Only" },
            { "DefaultStatsTitle", "Custom Unit Stats Comparison (No Custom Buffs)" },
            { "EnableBalance", "Enable Custom Unit Attribute Balance & Faction Traits" },
            { "TroopTemplateLabel", "Template:" },
            { "TroopTemplateSelect", "(Select Template)" },
            { "TroopTemplateBalanced", "Balanced Base Stats" },
            { "BtnTroopPreset", "Edit Troop File" },
            { "TroopPresetDefault", "Stats File: Default Template" },
            { "TroopPresetManual", "Stats File: Custom Config (Manual)" },
            { "TroopPresetFile", "Stats File: {0}" },
            { "TroopPresetLoaded", "Stats File: Loaded from Preset ({0})" },
            { "CurrentStatsTitle", "Current Unit Stats (Original vs. Current)" },
            { "GameSavesTitle", "In-Game Save List" },
            { "BackupsTitle", "Backup History List" },
            { "DetailTitle", "Save Details & Preview" },
            { "BackupSave", "Backup Save" },
            { "DeleteSave", "Delete Save" },
            { "Refresh", "Refresh" },
            { "RestoreBackup", "Restore Backup" },
            { "DeleteBackup", "Delete Backup" },
            { "LanguageLabel", "Language" },
            { "LangZhButton", "繁體中文" },
            { "LangEnButton", "English" },

            // Headers Default Grid
            { "HeaderName", "Unit Name" },
            { "HeaderIcon", "Icon" },
            { "HeaderType", "Type" },
            { "HeaderStyle", "Category" },
            { "HeaderHp", "HP" },
            { "HeaderMeleeDmg", "Melee Dmg" },
            { "HeaderRangedDmg", "Ranged Dmg" },
            { "HeaderMeleeRelt", "Melee Cooldown" },
            { "HeaderRangedRelt", "Ranged Cooldown" },
            { "HeaderVw", "Defense" },
            { "HeaderAw", "Combat Power" },
            { "HeaderSpeed", "Speed" },
            { "HeaderSight", "Sight" },
            { "HeaderRange", "Range/Skill Dist" },
            { "HeaderSpellRadius", "Spell Radius" },
            { "HeaderTier", "Tier" },

            // Headers Current Grid
            { "HeaderHpComp", "HP Comparison" },
            { "HeaderMeleeDmgComp", "Melee Dmg Comparison" },
            { "HeaderRangedDmgComp", "Ranged Dmg Comparison" },
            { "HeaderMeleeReltComp", "Melee Cooldown Comp" },
            { "HeaderRangedReltComp", "Ranged Cooldown Comp" },
            { "HeaderVwComp", "Defense Comparison" },
            { "HeaderAwComp", "Combat Comparison" },
            { "HeaderSpeedComp", "Speed Comparison" },
            { "HeaderSightComp", "Sight Comparison" },
            { "HeaderRangeComp", "Range Comparison" },
            { "HeaderSpellRadiusComp", "Spell Radius Comp" },

            // Save grid specific headers
            { "HeaderFolder", "Folder" },
            { "HeaderSaveTitle", "Save Title" },
            { "HeaderLevel", "Orig Level" },
            { "HeaderTime", "Save Time" },
            { "HeaderBackupFile", "Backup File" },
            { "HeaderBackupTime", "Backup Time" },
            { "HeaderOrigFolder", "Orig Folder" },

            // Tabs
            { "TabRoman", " Roman " },
            { "TabTeuton", " Teuton " },
            { "TabCelt", " Celt " },
            { "TabHun", " Hun " },

            // Dialog / Log / Message titles
            { "TitlePathError", "Path Error" },
            { "TitleConfirm", "Confirm Action" },
            { "TitleSuccess", "Success" },
            { "TitleError", "Error" },
            { "TitleWarning", "Confirm Overwrite" },
            { "TitleConfirmDelete", "Confirm Deletion" },
            { "TitleTips", "Tips" },

            // Dialog / Log / Message strings
            { "LogConstructCompleted", "Modifier form constructed. Loading data..." },
            { "LogLoadIconFailed", "Failed to load unit icon: " },
            { "LogDefaultStatsLoaded", "Custom unit stats loaded. Total {0} records." },
            { "LogDefaultStatsLoadError", "Error loading custom unit stats: " },
            { "LogBalanceToggled", "Custom unit attribute balance & faction traits {0}." },
            { "LogReadCurrent", "Reading current settings..." },
            { "LogReadCurrentDone", "Current settings read. Total {0} records for comparison." },
            { "LogPresetImportError", "Failed to read current settings: " },
            { "LogBrowseTitle", "Please select the Against Rome installation folder" },
            { "MsgSelectGameDir", "Please set the correct game path first." },
            { "MsgWrongGameDir", "The selected directory does not contain Against_Rome.exe. Please select the correct path." },
            { "MsgConfirmApply", "Are you sure you want to apply all changes?\nThis will overwrite game files." },
            { "MsgApplySuccess", "Changes successfully applied!" },
            { "MsgApplyFailed", "Failed to apply changes: " },
            { "MsgRestoreAllSuccess", "All original settings restored successfully!" },
            { "MsgRestoreStatsSuccess", "Unit stats restored successfully!" },
            { "MsgRestoreCompatSuccess", "Compatibility settings restored successfully!" },
            { "MsgRestoreLangSuccess", "Language settings restored successfully!" },
            { "MsgRestoreFailed", "Failed to restore: " },
            { "MsgExeNotFound", "Against_Rome.exe not found in game directory." },
            { "MsgLaunchFailed", "Failed to launch game: " },
            { "LogStartApply", "Applying changes..." },
            { "LogApplyAllSuccess", "All changes applied successfully!" },
            { "LogStartRestoreAll", "Restoring all original settings..." },
            { "LogRestoreAllDone", "All original settings successfully restored." },
            { "LogStartRestoreStats", "Restoring unit stats to original..." },
            { "LogRestoreStatsDone", "Unit stats successfully restored." },
            { "LogStartRestoreCompat", "Restoring compatibility to original..." },
            { "LogRestoreCompatDone", "Compatibility successfully restored." },
            { "LogStartRestoreLang", "Restoring language pack to original..." },
            { "LogRestoreLangDone", "Language successfully restored." },
            { "LogGameStarted", "Game successfully launched." },
            { "LogGamePathNotSetIcon", "Game path not set or invalid. Cannot load unit icons." },
            { "LogGuiDatNotFound", "gui.dat not found. Cannot load unit icons." },
            { "LogIconIniNotFound", "icon.ini not found in backup memory. Cannot load unit icons." },
            { "LogObjdefNotFound", "objdef.dau not found in backup memory. Cannot load custom unit stats." },
            { "LogNoObjdefForRead", "No objdef.dau file found to read." },
            { "LogSavePathNotSet", "Game path not set. Cannot load saves." },
            { "LogRefreshSavesFailed", "Failed to refresh save list: " },
            { "SaveDetailGameSave", "Save Type: Game Save\n\nFolder: {0}\n\nSave Title: {1}\n\nOriginal Level: {2}\n\nSave Time: {3}" },
            { "SaveDetailBackup", "Save Type: Backup File\n\nBackup File: {0}\n\nOriginal Folder: {1}\n\nSave Title: {2}\n\nOriginal Level: {3}\n\nBackup Time: {4}" },
            { "MsgSelectBackup", "Please select a backup to restore first." },
            { "MsgCannotResolveOrigFolder", "Cannot resolve the original folder for this backup. Cannot restore." },
            { "MsgGamePathNotSet", "Game path not set first. Cannot restore." },
            { "MsgConfirmOverwriteSave", "The target save folder [{0}] already exists. Overwrite?" },
            { "MsgRestoreBackupSuccess", "Backup restored successfully!" },
            { "MsgRestoreBackupFailed", "Failed to restore backup: " },
            { "MsgSelectSaveToDelete", "Please select a save to delete first." },
            { "MsgInvalidSaveDir", "Invalid save directory. Operation cancelled." },
            { "MsgConfirmDeleteSave", "Are you sure you want to permanently delete the save [{0}]? This action cannot be undone!" },
            { "MsgDeleteSaveSuccess", "Save deleted successfully!" },
            { "MsgDeleteSaveFailed", "Failed to delete save: " },
            { "MsgSelectBackupToDelete", "Please select a backup to delete first." },
            { "MsgConfirmDeleteBackup", "Are you sure you want to permanently delete the backup file [{0}]?" },
            { "MsgDeleteBackupSuccess", "Backup deleted successfully!" },
            { "MsgDeleteBackupFailed", "Failed to delete backup: " },
            { "MsgSelectSaveToBackup", "Please select a save to backup first." },
            { "MsgNoOrigFolderToBackup", "Cannot find the original folder for this save." },
            { "MsgBackupSaveSuccess", "Save backed up successfully!" },
            { "MsgBackupSaveFailed", "Failed to backup save: " },
            { "LogLoadTechDocFailed", "Failed to load technical document resource: " },
            { "Unparsable", "Unparsable" },
            { "Unknown", "Unknown" },
            { "LogBackupSaveSuccessDetail", "Save backup successful: {0} -> {1}" },
            { "LogBackupSaveFailedDetail", "Failed to backup save: " },
            { "LogRestoreBackupSuccessDetail", "Backup restore successful: {0} -> {1}" },
            { "LogRestoreBackupCleanupFailed", "The save was restored, but the old-save staging folder could not be removed: " },
            { "LogRestoreBackupFailedDetail", "Failed to restore backup: " },
            { "LogDeleteSaveSuccessDetail", "Deleted game save: {0}" },
            { "LogDeleteSaveFailedDetail", "Failed to delete save: " },
            { "LogDeleteBackupSuccessDetail", "Deleted backup file: {0}" },
            { "LogDeleteBackupFailedDetail", "Failed to delete backup: " },
            { "FocusLossTip", "Prevents the game from automatically pausing when the game window loses focus (runs in background)." },
            { "ModSkillsAndGloryTip", "Enable to apply the custom unit active skills, chief passive special abilities, leader glory growth, and aura settings configured in the Skill tab. Otherwise, standard default game values are written." },
            { "ToEngTip", "Forces the game interface and core text to English to avoid encoding issues." },
            { "DgVoodooTip", "Installs and enables dgVoodoo2 to fix graphics lag, low FPS, or black screens on Windows 10/11." },
            { "GameSpeedTip", "Speedhack-style scaling of the game's master clock so movement, production, combat and AI all run at 10x speed. Patches Against_Rome.exe and is fully reversible." },
            { "GeneralSkillsTip", "Greatly increases all passive special ability values of generals and chiefs by 5x." },
            { "LeaderGloryTip", "Multiplies each faction chief's glory-level attack/defense/damage growth and morale aura by 5x." },
            { "RangedRange3x", "3x Range for Ranged Units" },
            { "RangedRange3xTip", "Triples the attack and firing range of all ranged infantry, ranged cavalry, and siege weapons. Includes a built-in accuracy fix: the projectile impact damage radius is doubled (near misses now hit) and the random lead-aim scatter against moving targets is removed, so shots still connect at the longer range. Applies to all factions." },
            { "LogRangedRange3xToggled", "3x Range for Ranged Units {0}." },
            { "UnitMovementSpeed2x", "2x Movement Speed for Units" },
            { "UnitMovementSpeed2xTip", "Doubles the movement speed of all combat units (including soldiers, leaders, priests) and civilian units (villagers, packhorses)." },
            { "LogUnitMovementSpeed2xToggled", "2x Movement Speed for Units {0}." },
{ "SpellEntireMap", "Spell Casting Distance: Entire Map" },
{ "SpellEntireMapTip", "Raises priest spell and resurrection casting distance to the entire map; spell effect radius is unchanged." },
{ "LogSpellEntireMapToggled", "Spell Casting Distance: Entire Map {0}." },
{ "SpellRange3x", "3x Spell Effect Radius" },
{ "SpellRange3xTip", "Triples spell effect and hit radius from the original value; priest casting distance is unchanged." },
{ "LogSpellRange3xToggled", "3x Spell Effect Radius {0}." },
            { "ProjectileArcHeight", "2x Projectile Arc Height" },
            { "ProjectileArcHeightTip", "Raises projectile launch speed and gravity by 2x together: arrows, javelins and catapult stones fly 2x higher arcs that clear trees and buildings more easily, while landing point and flight time stay unchanged. Applies to all factions." },
            { "RomanEndlessTip", "Forces the player faction to Roman on all five endless maps. All three flags in the faction dialog will enter as Romans and may show no highlighted selection; the faction switch in Options can still be used manually to return to a barbarian faction. By original design Romans have no priest or glory skill tree; affects new games only." },
            { "FreeProdTip", "Makes all construction, building repairs, and unit production free (0 resource cost)." },
            { "FreeUpgradeTip", "Makes all formations, research, and attribute upgrades free (0 resource cost)." },
            { "NoSpellCostTip", "Priests and Druids consume no mana (0 MP cost) when casting spells." },
            { "InfiniteMoraleTip", "Locks unit morale at maximum, preventing retreat and keeping combat effectiveness." },
            { "BalanceTip", "Enables custom attribute balancing and faction traits for units." },
            { "NoSpellAltarTip", "Removes the requirement of having multiple altars to cast advanced spells." },
            { "SpellDamage5xTip", "Increases active combat and damage spell values by 5x for all factions." },
            { "SpellHealing10xTip", "Multiplies Kelt priest healing spell (Spell1) effects by 10x for rapid recovery." },
            { "SpellResurrectionTip", "Celtic resurrection restores units with 100% HP & morale, spawning Spearmen (male) or Heavy Infantry (female)." },
            { "MaxPopulationTip", "Increases the maximum game population limit to 1600." },
            { "HousingCapacity20xTip", "Increases the population capacity provided by tents and houses by 20x." },
            { "StorageCapacity10xTip", "Increases the resource storage capacity of Town Halls and Warehouses by 10x." },
            { "HqHp10xTip", "Increases the hit points (HP) of all Town Halls by 10x, significantly boosting base defense." },
            { "FastCiviProductionTip", "Increases the production or conversion speed of villagers by 10x." },
            { "FastBuildUpgradeRepairTip", "Increases building construction, upgrade, and repair speed by 10x." },
            { "FoodHealing10xTip", "Raises each automatic idle-regeneration tick from 1 HP to 10 HP while keeping the original interval. Decompilation confirms this path does not read or consume food resources." },
            { "CiviProduce20Tip", "Each click on the male/female production button in the residential tent panel now queues 20 civilians instead of 1 (clamped to remaining housing capacity — pair with 20x Housing Capacity). This is a player-only executable patch and does not affect AI villages." },
            { "VillageBuildRangeTip", "Sets the village construction/red-frame boundary radius to a very large value, allowing construction anywhere on the map." },
            { "AiM1Tip", "Endless mode: raises AI unit size from 6 to 20 members across all three paths (reinforcement units, reinforcement rebuild, and village day-to-day civilian conversion)." },
            { "AiM2Tip", "Endless mode: shortens reinforcement wait and scheduler loop delays and recycles completed NPC job slots so AI reinforcement waves arrive quickly and continuously." },
            { "AiM3Tip", "Endless mode: accelerates confirmed per-object cleanup of defeated AI villages and palisades, death detection, and retreat while preserving the vanilla safe terminal order." },
            { "AiM4Tip", "Endless mode: settle spots always found new settlements (respawn probability raised from a decaying chance to 101%)." },
            { "AiM5Tip", "Endless mode: AI settlements start with main-hall stockpiles to speed up their economy and army. Affects AI settlements only, never the player." },
            { "AiM6Tip", "Endless mode: raises the map's active-party cap from 4 to 40 so garrisons and patrols become far more numerous." },

            // Service-layer (PatchEngine / BackupManager) log messages
            { "SvcLogPreApplyRestore", "Restoring affected files to a clean state before applying, to clear leftover modifications..." },
            { "SvcLogFocusApplied", "Applied the no-pause-on-focus-loss patch." },
            { "SvcLogFocusRestored", "Restored the original pause-on-focus-loss behavior." },
            { "SvcLogVillageLegacyRestoreUnknown", "Cannot revert the legacy village build-range patch: executable signature mismatch." },
            { "SvcLogVillageLegacyRemoved", "Removed the legacy village build-range patch." },
            { "SvcLogVillageApplyUnknown", "Cannot apply the village build-range patch: executable signature mismatch." },
            { "SvcLogVillageApplied", "Applied the expanded village build-range patch." },
            { "SvcLogVillageRestored", "Restored the original village build-range." },
            { "SvcLogAltarApplied", "Applied the no-altar-requirement spell patch." },
            { "SvcLogAltarRestored", "Restored the original spell altar requirement." },
            { "SvcLogGameSpeedUnknown", "Unknown game clock constants detected; skipped the game-speed patch to avoid overwriting an unknown build." },
            { "SvcLogGameSpeedApplied", "Overall game speed: {0}x acceleration." },
            { "SvcLogGameSpeedOriginal", "Overall game speed: original (no acceleration)." },
            { "SvcLogTeamDatApplied", "Set the population cap to {0} in every map's team.dat ({1} files processed)." },
            { "SvcLogTeamDatRestored", "Restored the original population cap in every map's team.dat." },
            { "SvcLogTeamDatRoman", "Set the player faction to Roman in {0} endless maps (team.dat)." },
            { "SvcLogTeamDatRomanRestored", "Restored the original player faction in endless maps." },
            { "SvcLogRomanEndlessExeApplied", "Forced the endless-mode faction selector to Romans." },
            { "SvcLogRomanEndlessExeRestored", "Restored the original endless-mode faction selector." },
            { "SvcLogCiviProduce20Applied", "Set the residential tent production button to +20 per click." },
            { "SvcLogCiviProduce20Restored", "Restored the residential tent production button to +1 per click." },
            { "SvcLogRomanEndlessExeUnknown", "The Roman endless-mode EXE signature is unknown; the executable was left unchanged." },
            { "SvcLogRomanEndlessMismatch", "Warning: Roman endless-mode EXE and team.dat states disagree; the UI follows the EXE state." },
            { "SvcLogLeaderScriptMigrated", "Removed the legacy leader-glory script that caused combat crashes and rebuilt ak_anfuehrer.bci from the original." },
            { "SvcLogLangApplied", "Applied the English UI and map language pack." },
            { "SvcLogLangRestored", "Restored the original language files." },
            { "SvcLogDgvInstalled", "Installed and configured the dgVoodoo2 ({0}) graphics wrapper." },
            { "SvcLogDgvNotManaged", "Detected dgVoodoo2 components in the game folder that were not deployed by this modifier; they will not be deleted to protect your files. For a clean uninstall, manually remove DDraw.dll, D3D8.dll and dgVoodooCpl.exe from the game folder." },
            { "SvcLogDgvPreserved", "The managed dgVoodoo2 file {0} has been modified; it will be kept, not deleted." },
            { "SvcLogDgvRemoved", "Removed all modifier-managed dgVoodoo2 files." },
            { "SvcLogRestoredFile", "Restored: {0}" },
            { "SvcLogRestoredPopulation", "Restored population cap: {0}" },
            { "SvcLogDetectFailed", "[Detect] Failed to detect {0} state; options in this group will show as unchecked: {1}" },
            { "SvcLogBackupLoadedEmbedded", "Loaded the embedded Backup.zip baseline." },
            { "SvcLogBackupLoadedLocal", "Loaded Backup.zip from the program folder." },
            { "SvcLogBackupMissing", "No embedded or local Backup.zip found; select a valid game folder and the modifier will build an in-memory baseline from it." },
            { "SvcLogEparaHealed", "Rebuilt the in-memory backup entry SYSTEM/cl_epara.ini from the modifier's built-in clean defaults." },
            { "SvcLogEparaHealFailed", "Failed to rebuild backup entry SYSTEM/cl_epara.ini: {0}" },
            { "SvcLogEparaBuildFailed", "Failed to build the SYSTEM/cl_epara.ini backup from built-in defaults: {0}" },
            { "SvcLogAutoHealed", "Auto-restored missing backup entry from the game folder: {0}" },
            { "SvcLogAutoHealFailed", "Failed to auto-restore backup entry {0}: {1}" },
            { "SvcLogTeamDatHealed", "Auto-restored map team.dat backup entries from the game folder." },
            { "SvcLogTeamDatHealFailed", "Failed to auto-restore map team.dat backups: {0}" },
            { "SvcLogBackupIncomplete", "The backup source is missing required files; apply/restore may not run safely:" },
            { "SvcLogBackupFromGameDir", "Built a clean in-memory baseline from the selected game folder." }
        };
    }
}
