<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>..\AgainstRomeModifier.ico</ApplicationIcon>
    <ApplicationManifest>..\app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\src.Core\AgainstRome.Core.csproj" />
    <ProjectReference Include="..\src.MapEditor\AgainstRomeMapEditor.csproj" />
    <ProjectReference Include="..\src.SaveManager\AgainstRomeSaveManager.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\TechDoc.md" LogicalName="TechDoc.md" />
    <EmbeddedResource Include="..\TechDoc_EN.md" LogicalName="TechDoc_EN.md" />
  </ItemGroup>
</Project>
