using AgainstRomeMapEditor.Modules.Soundscape;
using Xunit;

namespace AgainstRomeMapEditor.Modules.Tests;

public sealed class SoundscapeEdgeAndGuardTests
{
    [Fact]
    public void BinaryStorage_SerializeToBinary_ThrowsOnNullSnapshot()
    {
        Assert.Throws<ArgumentNullException>(() => SoundscapeBinaryStorage.SerializeToBinary(null!));
    }

    [Fact]
    public void BinaryStorage_DeserializeFromBinary_ThrowsOnInsufficientHeaderLength()
    {
        byte[] tooShort = new byte[63];
        var ex = Assert.Throws<InvalidDataException>(() => SoundscapeBinaryStorage.DeserializeFromBinary(tooShort));
        Assert.Contains("64", ex.Message);
    }

    [Fact]
    public void BinaryStorage_DeserializeFromBinary_ThrowsOnInvalidMagicNumber()
    {
        byte[] invalidMagic = new byte[64];
        invalidMagic[0] = (byte)'B';
        invalidMagic[1] = (byte)'A';
        invalidMagic[2] = (byte)'D';
        invalidMagic[3] = (byte)'!';
        var ex = Assert.Throws<InvalidDataException>(() => SoundscapeBinaryStorage.DeserializeFromBinary(invalidMagic));
        Assert.Contains("魔數", ex.Message);
    }

    [Fact]
    public void BinaryStorage_DeserializeFromBinary_ThrowsOnUnsupportedVersion()
    {
        byte[] badVersion = new byte[64];
        badVersion[0] = (byte)'S';
        badVersion[1] = (byte)'N';
        badVersion[2] = (byte)'D';
        badVersion[3] = (byte)'Z';
        badVersion[4] = 99; // Version = 99
        badVersion[5] = 0;
        var ex = Assert.Throws<NotSupportedException>(() => SoundscapeBinaryStorage.DeserializeFromBinary(badVersion));
        Assert.Contains("99", ex.Message);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public void BinaryStorage_SaveToSoundDat_ThrowsOnInvalidPath(string? path)
    {
        var snapshot = new SoundscapeSnapshot("Amb_Plains", 0.5f, []);
        Assert.ThrowsAny<ArgumentException>(() => SoundscapeBinaryStorage.SaveToSoundDat(path!, snapshot));
    }

    [Fact]
    public void BinaryStorage_SaveToSoundDat_ThrowsOnNullSnapshot()
    {
        Assert.Throws<ArgumentNullException>(() => SoundscapeBinaryStorage.SaveToSoundDat("dummy.dat", null!));
    }

    [Fact]
    public void BinaryStorage_SaveToSoundDat_ThrowsNotSupportedException()
    {
        var snapshot = new SoundscapeSnapshot("Amb_Plains", 0.5f, []);
        var ex = Assert.Throws<NotSupportedException>(() => SoundscapeBinaryStorage.SaveToSoundDat("dummy.dat", snapshot));
        Assert.Contains("unwired", ex.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public void BinaryStorage_LoadFromSoundDat_ThrowsOnInvalidPath(string? path)
    {
        Assert.ThrowsAny<ArgumentException>(() => SoundscapeBinaryStorage.LoadFromSoundDat(path!));
    }

    [Fact]
    public void BinaryStorage_LoadFromSoundDat_ThrowsFileNotFoundException()
    {
        string nonExistent = Path.Combine(Path.GetTempPath(), "missing_sound_" + Guid.NewGuid().ToString("N") + ".dat");
        Assert.Throws<FileNotFoundException>(() => SoundscapeBinaryStorage.LoadFromSoundDat(nonExistent));
    }

    [Fact]
    public void BinaryStorage_ExportToJson_ThrowsOnNullSnapshot()
    {
        Assert.Throws<ArgumentNullException>(() => SoundscapeBinaryStorage.ExportToJson(null!));
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public void BinaryStorage_ImportFromJson_ThrowsOnInvalidJson(string? json)
    {
        Assert.ThrowsAny<ArgumentException>(() => SoundscapeBinaryStorage.ImportFromJson(json!));
    }

    [Fact]
    public void BinaryStorage_ExportToScript_ThrowsOnNullSnapshot()
    {
        Assert.Throws<ArgumentNullException>(() => SoundscapeBinaryStorage.ExportToScript(null!));
    }

    [Fact]
    public void BinaryStorage_ExportToScript_ThrowsNotSupportedException()
    {
        var snapshot = new SoundscapeSnapshot("Amb_Plains", 0.5f, []);
        var ex = Assert.Throws<NotSupportedException>(() => SoundscapeBinaryStorage.ExportToScript(snapshot));
        Assert.Contains("unwired", ex.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void EditorModule_GuardsAgainstNullArguments()
    {
        var module = new SoundscapeEditorModule();
        Assert.Throws<ArgumentNullException>(() => module.Load(null!));
        Assert.Throws<ArgumentNullException>(() => module.AddZone(null!));
        Assert.Throws<ArgumentNullException>(() => module.UpdateZone(null!));
        Assert.Throws<ArgumentNullException>(() => module.AddAutoGeneratedZones(null!));
    }

    [Fact]
    public void EditorModule_RemoveAndUpdate_NonExistentZone_ReturnsFalseWithoutDirtying()
    {
        var module = new SoundscapeEditorModule();
        Assert.False(module.IsDirty);

        bool removed = module.RemoveZone(Guid.NewGuid());
        Assert.False(removed);
        Assert.False(module.IsDirty);
        Assert.False(module.CanUndo);

        var ghostZone = new SoundscapeZone { Id = Guid.NewGuid(), Name = "Ghost" };
        bool updated = module.UpdateZone(ghostZone);
        Assert.False(updated);
        Assert.False(module.IsDirty);
        Assert.False(module.CanUndo);
    }

    [Fact]
    public void EditorModule_AddAutoGeneratedZones_EmptyIsNoOp()
    {
        var module = new SoundscapeEditorModule();
        module.AddAutoGeneratedZones([]);
        Assert.False(module.IsDirty);
        Assert.False(module.CanUndo);
        Assert.Empty(module.Zones);
    }

    [Fact]
    public void EditorModule_AutoGeneratedZones_LifecycleAndFiltering()
    {
        var module = new SoundscapeEditorModule();
        var manualZone = new SoundscapeZone { Name = "Manual Forge" };
        module.AddZone(manualZone);
        module.AcceptChanges();

        Assert.Equal(0, module.ClearAutoGeneratedZones());
        Assert.False(module.IsDirty);

        var autoZone1 = new SoundscapeZone { Name = "Auto River" };
        var autoZone2 = new SoundscapeZone { Name = "Auto Forest" };
        module.AddAutoGeneratedZones([autoZone1, autoZone2]);

        Assert.Equal(3, module.Zones.Count);
        Assert.True(module.Zones[1].Flags.HasFlag(SoundscapeZoneAttributes.IsAutoGenerated));
        Assert.True(module.Zones[2].Flags.HasFlag(SoundscapeZoneAttributes.IsAutoGenerated));

        int cleared = module.ClearAutoGeneratedZones();
        Assert.Equal(2, cleared);
        Assert.Single(module.Zones);
        Assert.Equal("Manual Forge", module.Zones[0].Name);
    }

    [Fact]
    public void EditorModule_UndoRedo_EmptyStack_ReturnsFalse()
    {
        var module = new SoundscapeEditorModule();
        Assert.False(module.CanUndo);
        Assert.False(module.Undo());
        Assert.False(module.CanRedo);
        Assert.False(module.Redo());
    }

    [Fact]
    public void EditorModule_GlobalAmbienceProperties_PushUndoOnlyOnValueChange()
    {
        var module = new SoundscapeEditorModule();
        string initialAmbience = module.GlobalAmbienceId;
        float initialVol = module.GlobalAmbienceVolume;

        // 設定相同值不應觸發 Undo
        module.GlobalAmbienceId = initialAmbience;
        Assert.False(module.CanUndo);

        module.GlobalAmbienceVolume = initialVol;
        Assert.False(module.CanUndo);

        // 設定新值觸發 Undo
        module.GlobalAmbienceId = "Amb_New_Track";
        Assert.True(module.CanUndo);
        Assert.Equal("Amb_New_Track", module.GlobalAmbienceId);

        module.Undo();
        Assert.Equal(initialAmbience, module.GlobalAmbienceId);

        module.GlobalAmbienceVolume = 0.95f;
        Assert.True(module.CanUndo);
        Assert.Equal(0.95f, module.GlobalAmbienceVolume, 3);

        module.Undo();
        Assert.Equal(initialVol, module.GlobalAmbienceVolume, 3);
    }

    [Fact]
    public void Catalog_CalculateDistanceToZone_ThrowsOnNullZone()
    {
        Assert.Throws<ArgumentNullException>(() => SoundscapeZoneCatalog.CalculateDistanceToZone(0f, 0f, null!));
    }

    [Fact]
    public void Catalog_PolygonDistanceAndInsideChecks_DegenerateVertices()
    {
        var emptyPoly = new SoundscapeZone
        {
            ShapeType = SoundscapeShapeType.ConvexPolygon,
            PolygonVertices = []
        };
        Assert.Equal(float.MaxValue, SoundscapeZoneCatalog.CalculateDistanceToZone(100f, 100f, emptyPoly));

        Assert.False(SoundscapeZoneCatalog.IsPointInsidePolygon(0f, 0f, null!));
        Assert.False(SoundscapeZoneCatalog.IsPointInsidePolygon(0f, 0f, [new(0, 0), new(10, 0)]));
    }

    [Fact]
    public void Catalog_DistancePointToSegment_DegenerateSegmentLengthZero()
    {
        // 長度為 0 的線段退化為單一點 (10, 10)
        float dist = SoundscapeZoneCatalog.DistancePointToSegment(13f, 14f, 10f, 10f, 10f, 10f);
        Assert.Equal(5f, dist, 2); // sqrt((13-10)^2 + (14-10)^2) = 5
    }

    [Fact]
    public void Catalog_CalculateAttenuation_EdgeCases()
    {
        // 內半徑大於等於外半徑：若距離大於外半徑 (如 250f > 100f) 則衰減為 0
        Assert.Equal(0f, SoundscapeZoneCatalog.CalculateAttenuation(250f, 200f, 100f, AttenuationCurveKind.Linear));

        // 距離等於內半徑：永遠為 1.0f (優先判定 distance <= innerRadius)
        Assert.Equal(1f, SoundscapeZoneCatalog.CalculateAttenuation(100f, 100f, 100f, AttenuationCurveKind.Linear));

        // 距離小於等於內半徑：永遠為 1.0f
        Assert.Equal(1f, SoundscapeZoneCatalog.CalculateAttenuation(0f, 50f, 200f, AttenuationCurveKind.Logarithmic));
        Assert.Equal(1f, SoundscapeZoneCatalog.CalculateAttenuation(50f, 50f, 200f, AttenuationCurveKind.Exponential));

        // 距離大於等於外半徑：永遠為 0.0f
        Assert.Equal(0f, SoundscapeZoneCatalog.CalculateAttenuation(300f, 50f, 200f, AttenuationCurveKind.SmoothStep));
    }

    [Fact]
    public void Catalog_Resolve_UnknownSoundId_ReturnsFallbackDefinition()
    {
        var catalog = new SoundscapeZoneCatalog();
        var def = catalog.Resolve("Unknown_Custom_Sound");
        Assert.NotNull(def);
        Assert.Equal("Unknown_Custom_Sound", def.SoundId);
        Assert.Equal(AudioCategory.AmbientZone, def.Category);
        Assert.Equal(SoundTriggerMode.ContinuousLoop, def.TriggerMode);
    }
}
