// Ghidra headless script that exports a reusable function inventory.
// Run with:
// analyzeHeadless <projectDir> <projectName> -process Against_Rome.exe \
//   -scriptPath tools/re -postScript GhidraFunctionInventory.java <outputDir> [decompile]
// @category AgainstRome

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;
import ghidra.program.model.symbol.Reference;
import ghidra.program.model.symbol.ReferenceIterator;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;

public class GhidraFunctionInventory extends GhidraScript {
    private static String csv(String value) {
        if (value == null) return "";
        return "\"" + value.replace("\"", "\"\"").replace("\r", " ").replace("\n", " ") + "\"";
    }

    private int countCallReferences(Function function) {
        int count = 0;
        ReferenceIterator refs = currentProgram.getReferenceManager().getReferencesTo(function.getEntryPoint());
        while (refs.hasNext()) {
            Reference ref = refs.next();
            if (ref.getReferenceType().isCall()) {
                count++;
            }
        }
        return count;
    }

    private String firstCallers(Function function, int limit) {
        StringBuilder sb = new StringBuilder();
        ReferenceIterator refs = currentProgram.getReferenceManager().getReferencesTo(function.getEntryPoint());
        int count = 0;
        while (refs.hasNext() && count < limit) {
            Reference ref = refs.next();
            if (!ref.getReferenceType().isCall()) continue;
            Function caller = getFunctionContaining(ref.getFromAddress());
            if (caller == null) continue;
            if (sb.length() > 0) sb.append(';');
            sb.append(caller.getEntryPoint()).append(':').append(caller.getName());
            count++;
        }
        return sb.toString();
    }

    private String decompile(DecompInterface ifc, Function function) {
        try {
            DecompileResults results = ifc.decompileFunction(function, 20, monitor);
            if (results != null && results.decompileCompleted() && results.getDecompiledFunction() != null) {
                return results.getDecompiledFunction().getC();
            }
            return "/* decompile failed */\n";
        } catch (Exception ex) {
            return "/* decompile exception: " + ex.getMessage() + " */\n";
        }
    }

    @Override
    protected void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length < 1) {
            throw new IllegalArgumentException("Expected output directory argument.");
        }

        File outputDir = new File(args[0]);
        if (!outputDir.exists() && !outputDir.mkdirs()) {
            throw new IllegalStateException("Unable to create output directory: " + outputDir);
        }

        boolean exportDecompile = args.length > 1 && args[1].equalsIgnoreCase("decompile");
        File csvFile = new File(outputDir, "against_rome_function_index.csv");
        File cFile = new File(outputDir, "against_rome_decompiled_functions.c");

        DecompInterface ifc = null;
        PrintWriter decompiledWriter = null;
        if (exportDecompile) {
            ifc = new DecompInterface();
            ifc.openProgram(currentProgram);
            decompiledWriter = new PrintWriter(new BufferedWriter(
                new OutputStreamWriter(new FileOutputStream(cFile), StandardCharsets.UTF_8)));
            decompiledWriter.println("/* Generated by GhidraFunctionInventory.java from " + currentProgram.getName() + ". */");
            decompiledWriter.println("/* This is machine-generated pseudocode for local reverse engineering, not original source. */");
        }

        int functionCount = 0;
        try (PrintWriter csvWriter = new PrintWriter(new BufferedWriter(
            new OutputStreamWriter(new FileOutputStream(csvFile), StandardCharsets.UTF_8)))) {
            csvWriter.println("entry,name,source_type,body_address_count,parameter_count,call_reference_count,first_callers,purpose_status");

            FunctionIterator functions = currentProgram.getFunctionManager().getFunctions(true);
            while (functions.hasNext()) {
                monitor.checkCancelled();
                Function function = functions.next();
                Address entry = function.getEntryPoint();
                int callRefs = countCallReferences(function);
                csvWriter.println(
                    csv(entry.toString()) + "," +
                    csv(function.getName()) + "," +
                    csv(function.getSymbol().getSource().toString()) + "," +
                    function.getBody().getNumAddresses() + "," +
                    function.getParameterCount() + "," +
                    callRefs + "," +
                    csv(firstCallers(function, 8)) + "," +
                    csv(function.getName().startsWith("FUN_") ? "unknown" : "named-or-candidate")
                );

                if (decompiledWriter != null && ifc != null) {
                    decompiledWriter.println();
                    decompiledWriter.println("/* ===== " + entry + " " + function.getName() + " ===== */");
                    decompiledWriter.print(decompile(ifc, function));
                }
                functionCount++;
                if (functionCount % 100 == 0) {
                    csvWriter.flush();
                    if (decompiledWriter != null) {
                        decompiledWriter.flush();
                    }
                    println("Export progress: " + functionCount + " functions");
                }
            }
        } finally {
            if (decompiledWriter != null) {
                decompiledWriter.flush();
                decompiledWriter.close();
            }
            if (ifc != null) {
                ifc.dispose();
            }
        }

        println("Exported " + functionCount + " functions to " + csvFile.getAbsolutePath());
        if (exportDecompile) {
            println("Exported decompiled pseudocode to " + cFile.getAbsolutePath());
        }
    }
}
